# Generated by Django 4.2.3 on 2023-10-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Number', models.IntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('Message', models.TextField()),
            ],
        ),
    ]
