# Generated by Django 4.2.5 on 2023-10-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlo', '0002_alter_contactus_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Number',
            field=models.CharField(max_length=10),
        ),
    ]
