# Generated by Django 5.0 on 2024-06-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='saveimg',
            field=models.ImageField(blank=True, null=True, upload_to='imges'),
        ),
    ]
